### ISSUE TITLE
entering number by keyboard

### ISSUE THREAD

**Issue by sanchi** [saycel/webph.one#79]
on Desktop, it would be nice to be able to enter the number with the keyboard

**Comment by rodrigomonelos** [comment]
Done!

**Comment by gmarcos87** [comment]
It is still missing to implement the delete key and the enter key to dial.

**Comment by rodrigomonelos** [comment]
Ok, already taken into the backlog
